server:
  port: 8888
  
#配置redis
spring.redis.host: localhost
spring.redis.port: 6379
#数据库连接配置
#datasource:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://127.0.0.1:3306/zqHomeManage?characterEncoding=utf-8&useSSL=false
#  username: admin
#  password: admin
#
##mybatis的相关配置
#mybatis:
#  #mapper配置文件
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.zq.springboot.dao.*